[project]
name = "yet-another-python-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.13.8",
    "requests>=2.32.3",
]
